### ISSUE TITLE
(HU03) Generar roadmap

### ISSUE THREAD

**Issue by sidarragac** [sidarragac/JobJourney#32]
# Descripción:
Como usuario quiero tener un roadmap que me guie a mi trabajo soñado.
# Criterios de aceptación:
- [x] Cuando el usuario provee la información acorde al objetivo, interés y salario esperado, se debe cumplir que el sistema creará, con inteligencia artificial, el roadmap escalonado hasta mi objetivo.
- [x] Cuando el usuario recibe el roadmap, se debe cumplir que el sistema proveerá recomendaciones con los que me podría ayudar para trabajar en cada escalón.
- [x] Cuando el usuario recibe el roadmap, se debe cumplir que el sistema proveerá un listado de subtareas para cada escalón.
- [x] Cuando el usuario recibe el roadmap, se debe cumplir que el sistema mostrara en cada paso del roadmap un trabajo al que debería aspirar.
